#!/usr/bin/env bash
# install.sh — set up tech-radar on a Linux server (Debian/Ubuntu).
#
# Idempotent: safe to re-run. Installs Docker Engine + compose plugin if absent,
# initialises .env if missing, builds the image, brings up the container.
#
# Usage:
#   ./install.sh                              # interactive (prompts for key)
#   OPENROUTER_API_KEY=sk-or-v1-... ./install.sh   # non-interactive
#   PORT=9090 ./install.sh                    # custom host port (default 8080)
#   ./install.sh --no-key                     # skip .env setup entirely
#   ./install.sh --skip-docker-install        # docker already present, just deploy
#   ./install.sh --no-start                   # build but don't start
#
# Environment variables (all optional):
#   OPENROUTER_API_KEY  — written to .env if provided
#   GITHUB_TOKEN        — written to .env if provided
#   PORT                — host port (default 8080)

set -euo pipefail

# ----- pretty logs --------------------------------------------------
log()  { printf '\033[36m[install]\033[0m %s\n' "$*"; }
warn() { printf '\033[33m[install]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[31m[install]\033[0m %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

# ----- arg parsing --------------------------------------------------
SKIP_DOCKER_INSTALL=0
SKIP_KEY=0
NO_START=0
for arg in "$@"; do
  case "$arg" in
    --skip-docker-install) SKIP_DOCKER_INSTALL=1 ;;
    --no-key)              SKIP_KEY=1 ;;
    --no-start)            NO_START=1 ;;
    -h|--help)             grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "unknown arg: $arg (use --help)" ;;
  esac
done

PORT="${PORT:-8080}"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$PROJECT_DIR"

# ----- sanity checks ------------------------------------------------
[[ -f Dockerfile ]]         || die "Dockerfile not found in $PROJECT_DIR — wrong directory?"
[[ -f docker-compose.yml ]] || die "docker-compose.yml not found — re-clone the project."

# ----- docker install (apt-only) ------------------------------------
need_sudo() {
  if [[ $EUID -ne 0 ]] && command -v sudo >/dev/null; then
    echo "sudo"
  else
    echo ""
  fi
}
SUDO="$(need_sudo)"

install_docker() {
  if [[ "$SKIP_DOCKER_INSTALL" == "1" ]]; then
    log "skipping docker install (--skip-docker-install)"
    return
  fi
  if command -v docker >/dev/null && docker compose version >/dev/null 2>&1; then
    log "docker + compose plugin already present — skipping install"
    return
  fi
  if ! command -v apt-get >/dev/null; then
    die "This script auto-installs docker only on Debian/Ubuntu (apt-based).
         On other distros: install docker engine + compose plugin manually,
         then re-run with --skip-docker-install."
  fi

  log "installing docker engine + compose plugin via apt..."
  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq ca-certificates curl gnupg

  # Docker official APT repo
  $SUDO install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.gpg ]]; then
    curl -fsSL https://download.docker.com/linux/debian/gpg | \
      $SUDO gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    $SUDO chmod a+r /etc/apt/keyrings/docker.gpg
  fi
  CODENAME="$(. /etc/os-release && echo "${VERSION_CODENAME:-bookworm}")"
  OS_ID="$(. /etc/os-release && echo "$ID")"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/$OS_ID $CODENAME stable" | \
    $SUDO tee /etc/apt/sources.list.d/docker.list > /dev/null

  $SUDO apt-get update -qq
  $SUDO apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
       docker-buildx-plugin docker-compose-plugin

  # Add current user to docker group so subsequent runs don't need sudo.
  if [[ $EUID -ne 0 ]] && ! groups "$USER" | grep -qw docker; then
    log "adding $USER to docker group (re-login required for non-sudo access)"
    $SUDO usermod -aG docker "$USER"
  fi
}

# ----- .env setup ---------------------------------------------------
ensure_env() {
  if [[ "$SKIP_KEY" == "1" ]]; then
    log "skipping .env setup (--no-key)"
    return
  fi
  if [[ -f .env ]] && grep -q '^OPENROUTER_API_KEY=' .env; then
    if grep -q '^OPENROUTER_API_KEY=$' .env; then
      warn ".env exists but OPENROUTER_API_KEY is empty — will leave it (mock mode only)"
    else
      log ".env already has OPENROUTER_API_KEY — keeping"
    fi
    return
  fi

  local key="${OPENROUTER_API_KEY:-}"
  local gh="${GITHUB_TOKEN:-}"

  if [[ -z "$key" ]] && [[ -t 0 ]]; then
    printf "OPENROUTER_API_KEY (Enter to skip — UI will only allow mock mode): "
    read -r key
  fi
  if [[ -z "$gh" ]] && [[ -t 0 ]]; then
    printf "GITHUB_TOKEN (Enter to skip — works without, but rate-limited): "
    read -r gh
  fi

  {
    echo "# Auto-generated by install.sh. Do not commit."
    [[ -n "$key" ]] && echo "OPENROUTER_API_KEY=$key" || echo "# OPENROUTER_API_KEY="
    [[ -n "$gh" ]] && echo "GITHUB_TOKEN=$gh" || echo "# GITHUB_TOKEN="
  } > .env
  chmod 600 .env
  log ".env written ($([[ -n "$key" ]] && echo 'with' || echo 'without') OpenRouter key)"
}

# ----- build & start ------------------------------------------------
COMPOSE() {
  # Prefer 'docker compose' (plugin), fall back to legacy 'docker-compose'
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  else
    docker-compose "$@"
  fi
}

bring_up() {
  log "building image..."
  PORT="$PORT" COMPOSE build

  if [[ "$NO_START" == "1" ]]; then
    log "build only — skipping start (--no-start)"
    return
  fi

  log "starting container (host port $PORT)..."
  PORT="$PORT" COMPOSE up -d
  sleep 2
  COMPOSE ps
}

# ----- main ---------------------------------------------------------
main() {
  log "tech-radar install in $PROJECT_DIR"
  install_docker
  ensure_env
  bring_up

  # Final probe
  local url="http://localhost:$PORT"
  if curl -fsS "$url/api/state" >/dev/null 2>&1; then
    log "OK — UI reachable at $url"
    curl -fsS "$url/api/state" | python3 -c \
      'import sys,json; d=json.loads(sys.stdin.read());
print("  mode:", d.get("mode"));
print("  openrouter_key_present:", d.get("openrouter_key_present"));
print("  items:", d.get("items_total"), "ranked:", d.get("ranked_count"))' 2>/dev/null || true
  else
    warn "container is up, but $url/api/state didn't respond — check 'docker compose logs'"
  fi
}

main "$@"
